config/routes.rb
Rails.application.routes.draw do
  resources :female_transaksis
  resources :male_transaksis
  resources :koleksi_jurnals
  resources :akuns
  devise_for :users
end

app/models/akun.rb
class Akun < ApplicationRecord
  belongs_to :tipe_akun
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/female_transaksi.rb
class FemaleTransaksi < ApplicationRecord
  belongs_to :akun
  belongs_to :tipe_relasi
  belongs_to :jurnal
end

app/models/jurnal.rb
class Jurnal < ApplicationRecord
  belongs_to :koleksi_jurnal
  has_many :male_transaksis
  has_many :female_transaksis
end

app/models/koleksi_jurnal.rb
class KoleksiJurnal < ApplicationRecord
  belongs_to :user
  has_many :jurnals
end

app/models/male_transaksi.rb
class MaleTransaksi < ApplicationRecord
  belongs_to :akun
  belongs_to :tipe_relasi
  belongs_to :jurnal
end

app/models/tipe_akun.rb
class TipeAkun < ApplicationRecord
end

app/models/tipe_relasi.rb
class TipeRelasi < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :akuns
  has_many :jurnals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/akuns_controller.rb
class AkunsController < ApplicationController
  before_action :set_akun, only: [:show, :edit, :update, :destroy]

  # GET /akuns
  def index
    @akuns = Akun.all
  end

  # GET /akuns/1
  def show
  end

  # GET /akuns/new
  def new
    @akun = Akun.new
  end

  # GET /akuns/1/edit
  def edit
  end

  # POST /akuns
  def create
    @akun = Akun.new(akun_params)

    if @akun.save
      redirect_to @akun, notice: 'Akun was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /akuns/1
  def update
    if @akun.update(akun_params)
      redirect_to @akun, notice: 'Akun was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /akuns/1
  def destroy
    @akun.destroy
    redirect_to akuns_url, notice: 'Akun was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akun
      @akun = Akun.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def akun_params
      params.require(:akun).permit(:kode, :nama, :tipe_akun_id, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/female_transaksis_controller.rb
class FemaleTransaksisController < ApplicationController
  before_action :set_female_transaksi, only: [:show, :edit, :update, :destroy]

  # GET /female_transaksis
  def index
    @female_transaksis = FemaleTransaksi.all
  end

  # GET /female_transaksis/1
  def show
  end

  # GET /female_transaksis/new
  def new
    @female_transaksi = FemaleTransaksi.new
  end

  # GET /female_transaksis/1/edit
  def edit
  end

  # POST /female_transaksis
  def create
    @female_transaksi = FemaleTransaksi.new(female_transaksi_params)

    if @female_transaksi.save
      redirect_to @female_transaksi, notice: 'Female transaksi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /female_transaksis/1
  def update
    if @female_transaksi.update(female_transaksi_params)
      redirect_to @female_transaksi, notice: 'Female transaksi was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /female_transaksis/1
  def destroy
    @female_transaksi.destroy
    redirect_to female_transaksis_url, notice: 'Female transaksi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_female_transaksi
      @female_transaksi = FemaleTransaksi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def female_transaksi_params
      params.require(:female_transaksi).permit(:akun_id, :deskripsi, :nominal, :tipe_relasi_id, :jurnal_id)
    end
end

app/controllers/koleksi_jurnals_controller.rb
class KoleksiJurnalsController < ApplicationController
  before_action :set_koleksi_jurnal, only: [:show, :edit, :update, :destroy]

  # GET /koleksi_jurnals
  def index
    @koleksi_jurnals = KoleksiJurnal.all
  end

  # GET /koleksi_jurnals/1
  def show
  end

  # GET /koleksi_jurnals/new
  def new
    @koleksi_jurnal = KoleksiJurnal.new
  end

  # GET /koleksi_jurnals/1/edit
  def edit
  end

  # POST /koleksi_jurnals
  def create
    @koleksi_jurnal = KoleksiJurnal.new(koleksi_jurnal_params)

    if @koleksi_jurnal.save
      redirect_to @koleksi_jurnal, notice: 'Koleksi jurnal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /koleksi_jurnals/1
  def update
    if @koleksi_jurnal.update(koleksi_jurnal_params)
      redirect_to @koleksi_jurnal, notice: 'Koleksi jurnal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /koleksi_jurnals/1
  def destroy
    @koleksi_jurnal.destroy
    redirect_to koleksi_jurnals_url, notice: 'Koleksi jurnal was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koleksi_jurnal
      @koleksi_jurnal = KoleksiJurnal.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def koleksi_jurnal_params
      params.require(:koleksi_jurnal).permit(:user_id)
    end
end

app/controllers/male_transaksis_controller.rb
class MaleTransaksisController < ApplicationController
  before_action :set_male_transaksi, only: [:show, :edit, :update, :destroy]

  # GET /male_transaksis
  def index
    @male_transaksis = MaleTransaksi.all
  end

  # GET /male_transaksis/1
  def show
  end

  # GET /male_transaksis/new
  def new
    @male_transaksi = MaleTransaksi.new
  end

  # GET /male_transaksis/1/edit
  def edit
  end

  # POST /male_transaksis
  def create
    @male_transaksi = MaleTransaksi.new(male_transaksi_params)

    if @male_transaksi.save
      redirect_to @male_transaksi, notice: 'Male transaksi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /male_transaksis/1
  def update
    if @male_transaksi.update(male_transaksi_params)
      redirect_to @male_transaksi, notice: 'Male transaksi was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /male_transaksis/1
  def destroy
    @male_transaksi.destroy
    redirect_to male_transaksis_url, notice: 'Male transaksi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_male_transaksi
      @male_transaksi = MaleTransaksi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def male_transaksi_params
      params.require(:male_transaksi).permit(:akun_id, :deskripsi, :nominal, :tipe_relasi_id, :jurnal_id)
    end
end

app/helpers/akuns_helper.rb
module AkunsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/female_transaksis_helper.rb
module FemaleTransaksisHelper
end

app/helpers/koleksi_jurnals_helper.rb
module KoleksiJurnalsHelper
end

app/helpers/male_transaksis_helper.rb
module MaleTransaksisHelper
end

app/views/akuns/_form.html.erb
<%= form_for(@akun, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @akun.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@akun.errors.count, "error") %> prohibited this akun from being saved:</h4>

      <ul>
      <% @akun.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :kode, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :kode, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nama, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nama, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tipe_akun, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tipe_akun, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/akuns/edit.html.erb
<div class="page-header">
  <%= link_to akuns_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @akun, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing akun</h1>
</div>

<%= render 'form' %>

app/views/akuns/index.html.erb
<div class="page-header">
  <%= link_to new_akun_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Akun
  <% end %>
  <h1>Listing akuns</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Kode</th>
            <th>Nama</th>
            <th>Tipe akun</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @akuns) do |akun| %>
            <td><%= akun.kode %></td>
            <td><%= akun.nama %></td>
            <td><%= akun.tipe_akun %></td>
            <td><%= akun.user %></td>
            <td><%= link_to 'Show', akun %></td>
        <td><%= link_to 'Edit', edit_akun_path(akun) %></td>
        <td><%= link_to 'Destroy', akun, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/akuns/new.html.erb
<div class="page-header">
  <%= link_to akuns_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New akun</h1>
</div>

<%= render 'form' %>

app/views/akuns/show.html.erb
<div class="page-header">
  <%= link_to akuns_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_akun_path(@akun), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show akun</h1>
</div>

<dl class="dl-horizontal">
  <dt>Kode:</dt>
  <dd><%= @akun.kode %></dd>

  <dt>Nama:</dt>
  <dd><%= @akun.nama %></dd>

  <dt>Tipe akun:</dt>
  <dd><%= @akun.tipe_akun %></dd>

  <dt>User:</dt>
  <dd><%= @akun.user %></dd>

</dl>

app/views/female_transaksis/_form.html.erb
<%= form_for(@female_transaksi, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @female_transaksi.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@female_transaksi.errors.count, "error") %> prohibited this female_transaksi from being saved:</h4>

      <ul>
      <% @female_transaksi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :akun, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :akun, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deskripsi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :deskripsi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nominal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nominal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tipe_relasi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tipe_relasi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jurnal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :jurnal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/female_transaksis/edit.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @female_transaksi, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing female_transaksi</h1>
</div>

<%= render 'form' %>

app/views/female_transaksis/index.html.erb
<div class="page-header">
  <%= link_to new_female_transaksi_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Female transaksi
  <% end %>
  <h1>Listing female_transaksis</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Akun</th>
            <th>Deskripsi</th>
            <th>Nominal</th>
            <th>Tipe relasi</th>
            <th>Jurnal</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @female_transaksis) do |female_transaksi| %>
            <td><%= female_transaksi.akun %></td>
            <td><%= female_transaksi.deskripsi %></td>
            <td><%= female_transaksi.nominal %></td>
            <td><%= female_transaksi.tipe_relasi %></td>
            <td><%= female_transaksi.jurnal %></td>
            <td><%= link_to 'Show', female_transaksi %></td>
        <td><%= link_to 'Edit', edit_female_transaksi_path(female_transaksi) %></td>
        <td><%= link_to 'Destroy', female_transaksi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/female_transaksis/new.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New female_transaksi</h1>
</div>

<%= render 'form' %>

app/views/female_transaksis/show.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_female_transaksi_path(@female_transaksi), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show female_transaksi</h1>
</div>

<dl class="dl-horizontal">
  <dt>Akun:</dt>
  <dd><%= @female_transaksi.akun %></dd>

  <dt>Deskripsi:</dt>
  <dd><%= @female_transaksi.deskripsi %></dd>

  <dt>Nominal:</dt>
  <dd><%= @female_transaksi.nominal %></dd>

  <dt>Tipe relasi:</dt>
  <dd><%= @female_transaksi.tipe_relasi %></dd>

  <dt>Jurnal:</dt>
  <dd><%= @female_transaksi.jurnal %></dd>

</dl>

app/views/koleksi_jurnals/_form.html.erb
<%= form_for(@koleksi_jurnal, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @koleksi_jurnal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@koleksi_jurnal.errors.count, "error") %> prohibited this koleksi_jurnal from being saved:</h4>

      <ul>
      <% @koleksi_jurnal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/koleksi_jurnals/edit.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @koleksi_jurnal, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing koleksi_jurnal</h1>
</div>

<%= render 'form' %>

app/views/koleksi_jurnals/index.html.erb
<div class="page-header">
  <%= link_to new_koleksi_jurnal_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Koleksi jurnal
  <% end %>
  <h1>Listing koleksi_jurnals</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @koleksi_jurnals) do |koleksi_jurnal| %>
            <td><%= koleksi_jurnal.user %></td>
            <td><%= link_to 'Show', koleksi_jurnal %></td>
        <td><%= link_to 'Edit', edit_koleksi_jurnal_path(koleksi_jurnal) %></td>
        <td><%= link_to 'Destroy', koleksi_jurnal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/koleksi_jurnals/new.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New koleksi_jurnal</h1>
</div>

<%= render 'form' %>

app/views/koleksi_jurnals/show.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_koleksi_jurnal_path(@koleksi_jurnal), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show koleksi_jurnal</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @koleksi_jurnal.user %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Akutansi</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Akutansi", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right nav">
          <% if user_signed_in? %>
            <li><a href="/akuns">Akun</a></li>
            <li><a href="/jurnals">Jurnal</a></li>
            <li><a href="/buku-besar">Buku Besar</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/users/sign_out">Sign Out</a></li>
              </ul>
            </li>
          <% else %>
            <li><a href="/users/sign_in">Sign In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/male_transaksis/edit.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @male_transaksi, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing male_transaksi</h1>
</div>

<%= render 'form' %>

app/views/male_transaksis/index.html.erb
<div class="page-header">
  <%= link_to new_male_transaksi_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Male transaksi
  <% end %>
  <h1>Listing male_transaksis</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Akun</th>
            <th>Deskripsi</th>
            <th>Nominal</th>
            <th>Tipe relasi</th>
            <th>Jurnal</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @male_transaksis) do |male_transaksi| %>
            <td><%= male_transaksi.akun %></td>
            <td><%= male_transaksi.deskripsi %></td>
            <td><%= male_transaksi.nominal %></td>
            <td><%= male_transaksi.tipe_relasi %></td>
            <td><%= male_transaksi.jurnal %></td>
            <td><%= link_to 'Show', male_transaksi %></td>
        <td><%= link_to 'Edit', edit_male_transaksi_path(male_transaksi) %></td>
        <td><%= link_to 'Destroy', male_transaksi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/male_transaksis/new.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New male_transaksi</h1>
</div>

<%= render 'form' %>

app/views/male_transaksis/show.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_male_transaksi_path(@male_transaksi), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show male_transaksi</h1>
</div>

<dl class="dl-horizontal">
  <dt>Akun:</dt>
  <dd><%= @male_transaksi.akun %></dd>

  <dt>Deskripsi:</dt>
  <dd><%= @male_transaksi.deskripsi %></dd>

  <dt>Nominal:</dt>
  <dd><%= @male_transaksi.nominal %></dd>

  <dt>Tipe relasi:</dt>
  <dd><%= @male_transaksi.tipe_relasi %></dd>

  <dt>Jurnal:</dt>
  <dd><%= @male_transaksi.jurnal %></dd>

</dl>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>